### ISSUE TITLE
Easing will not work in IE8, e.g. with "easInExpo"

### ISSUE THREAD

**Issue by julmot** [gdsmith/jquery.easing#11]
I'm using the plugin in IE8 and saw a strange issue
![easing](https://cloud.githubusercontent.com/assets/8310677/6104863/9a387a70-b051-11e4-80ca-6c2393b214af.png)
The effect will not work in IE8 and also there is this strange invalid attribute "easing" on the animate-element. @gdsmith Can you give some informations about this issue and maybe also about the browser compatibility?

**Comment by gdsmith** [comment]
No idea about that, it was written before IE8 was available so compatability should be pretty good. I don't have a working version of IE8 to test on, but if you can give me a complete example of the code that led to the issue perhaps that might help.
