### ISSUE TITLE
License document

### ISSUE THREAD

**Issue by Kandy16** [gdsmith/jquery.easing#12]
Hey,
 Thanks for the good effort in building this library. We would like to use your node in our project. 

Can you let us know what license have been assigned to this library?

Thanks
Kandy

**Comment by Kandy16** [comment]
Hey Everyone,

We have built a commercial application using your node and have hold our release because of the lack of license information of this particular module. There is a bit of urgency and pressure on us to make the release.

I request you to reveal the license information as soon as possible which will be very helpful for us.

Thanks In Advance
Kandy

**Comment by gdsmith** [comment]
Hey Kandy

Have you looked at what you are using? The license is in the file:

>  Open source under the BSD License. 

Hope that helps.
