### ISSUE TITLE
Redo release tag for bower

### ISSUE THREAD

**Issue by cvn** [gdsmith/jquery.easing#15]
The latest release tag is pointing to a commit (979dcad) that is missing the bower.json file, and so bower can not read the project metadata, (main file, etc).

Can you delete the `1.3.2` tag and recreate it at commit bbb5727? Or make a new release?

Once this is done, it will fix Issue #14.

PS. I made a request to the bower folks to point the `jquery.easing` bower package to this repo instead of the  bower-jquery-easing fork: bower/registry#165

**Comment by gdsmith** [comment]
Should be fixed now
