### ISSUE TITLE
Google PageSpeed reports that the minified version needs optimizing further

### ISSUE THREAD

**Issue by whiztler** [gdsmith/jquery.easing#18]
Google pagespeed report:

Minify JavaScript
Compacting JavaScript code can save many bytes of data and speed up downloading, parsing, and execution time.
Minify JavaScript for the following resources to reduce their size by 991B (53% reduction).
Minifying https://cdnjs.cloudflare.com/…s/jquery-easing/1.3/jquery.easing.min.js could save 991B (53% reduction) after compression.

> Improving the min.js version improves PageSpeed score and therefore your SEO

**Comment by gdsmith** [comment]
Fixed in 1.4
