### ISSUE TITLE
Low quality source code

### ISSUE THREAD

**Issue by DelvarWorld** [gdsmith/jquery.easing#20]
The source code of this library is written as if it were minified code, and it also has lots of redundant logic problems. I'm trying to expand this into non-jQuery functions to use in another library which is why I've discovered these cases.

For example these lines of code:

https://github.com/gdsmith/jquery.easing/blob/master/jquery.easing.js#L104-L111

There's a few things here that are undesirable in source code:

 - One letter variable names, including the fn parameters, making debugging difficult / impossible. Fortunately [this StackOverflow answer](http://stackoverflow.com/questions/7758125/customize-jquery-easeoutelastic-function) is helpful.
 - The highlighted function first hard codes `var p = 0;` and then checks `if (!p) p=d*(.3*1.5); `. Things like this could be avoided for efficiency, and make the source code more readable.
 - Incorrect javascript scoping is used, in the same function `var s=1.70158;` and then `else var s =` you can see `s` is redefined incorrectly using a second `var` declaration
 - Inline operators are used in if statements such as `if ((t/=d/2)==2)` which mutates the variable `t` in place, making tracing code unnecessarily difficult.
 - In general these functions aren't written like source code. They're written like (poorly) hand optimized, (poorly) hand minified functions that would be better left to Uglify or Closure Compiler work on them.

Since these functions have clearly stood the test of time the logic in them is sound and doesn't **need** to change for the library to work. For a learning opportunity, however, there is much room for improvement.

**Comment by DelvarWorld** [comment]
I just opened sourced https://github.com/DelvarWorld/easing-functions to address all of these issues and use the algorithms in an agnostic environment

**Comment by nonameolsson** [comment]
I'm having a low of warnings when using it JSHint and Gulp. The quality could be improved.

**Comment by gdsmith** [comment]
Fixed in 1.4
