### ISSUE TITLE
BUG with new version of jquery easing

### ISSUE THREAD

**Issue by batata004** [gdsmith/jquery.easing#26]
Hi,

I am updating some of my plugin but some weird bug is happening with jquery easing. Using the old version (1.3) the problem does not happen, using the new version the problem happens.

Both codes below are absolutely exactly the same. Nothing is different except the version of jquery easing.

https://quemfazsite.com.br/temp/teste-old-easing.php
https://quemfazsite.com.br/temp/teste-new-easing.php

Open the first link (old) and click GO1 and GO2. You will see an animation in the background color. When you open the second link and click in GO1 and GO2 you will see the animation works strangely, a black background appears in the element.

The strangest thing here is that I am not even using EASING in this page! The animation is being done with the default, LINEAR but no other fancy easing is being used and even so jquery easing messes with the animation.

Can we expect a solution soon?

**Comment by gdsmith** [comment]
Hi @batata004 it looks like your using an older version of jQuery, so for that version you should definitely be using the older version of jquery.easing plugin. Can you try the same thing with the latest version of jQuery?

**Comment by batata004** [comment]
My friend, I am using the latest version of jquery that belongs to 1.x.

I cant use 2.x nor 3.x cause I really need to have jquery compatible with the most browsers possible. If I use 2.x or 3x. as _per specification_ many old browser were ignored.

But the 1.12.4 is the latest official jquery version to the 1.x branch.

**Comment by gdsmith** [comment]
For pre`2.x` versions of jquery you will need to use the `1.3` version of the easing plugin.

**Comment by dmethvin** [comment]
The jQuery core default easing is `"swing"` not `"linear"`. Note that the plugin [does change the default easing behavior](https://github.com/gdsmith/jquery.easing/blob/17566b320c7b6b5ea04c8e7672a4c2b5989b3dcb/jquery.easing.js#L54-L57) so that would explain why including it changes the behavior.
