### ISSUE TITLE
Require jquery.easing returns blank object?

### ISSUE THREAD

**Issue by FireController1847** [gdsmith/jquery.easing#30]
When searching for jquery.easing in the node.js modules folder, I couldn't find it, and when I require it, it just returns a blank object. Does the module still work?

**Comment by brettz9** [comment]
It probably works in the browser, but there is a bug for CommonJS in that the function should return `$` at the end (this bug will affect AMD also).

And nowadays, it'd be nice to switch to ESM in source, and use Rollup or such to create UMD and ESM distributions from that.
