### ISSUE TITLE
Link to LICENSE in jquery.easing.js is not correct

### ISSUE THREAD

**Issue by viniciusfacco** [gdsmith/jquery.easing#36]
I just found out that the link to the license in file jquery.easing.js is not correct. 

The link in line 6 is: [https://raw.github.com/gdsmith/jquery-easing/master/LICENSE](https://raw.github.com/gdsmith/jquery-easing/master/LICENSE)

The correct link should be: [https://raw.github.com/gdsmith/jquery.easing/master/LICENSE](https://raw.github.com/gdsmith/jquery.easing/master/LICENSE)

The correct substring in the link is "jquery.easing" instead of "jquery-easing".

**Comment by gdsmith** [comment]
Updated, thanks
