### ISSUE TITLE
Creating this plugin to be AMD compliant?

### ISSUE THREAD

**Issue by nmatthew123** [gdsmith/jquery.easing#9]
This is more of a comment/query. I am trying to include this plugin using requirejs and I am having a lot of issues with this loading. I have tried to shim it but with no luck. Will this plugin be rewritten to be AMD compliant?

**Comment by julmot** [comment]
+1

**Comment by ryantan** [comment]
This worked for me

    requirejs.config({
      paths: {
        "jquery": "../bower_components/jquery/dist/jquery.min",
        "jScrollPane": "../bower_components/jScrollPane/script/jquery.jscrollpane",
        "jquery.mousewheel": "../bower_components/jScrollPane/script/jquery.mousewheel",
        "jquery.easing": "../bower_components/jquery.easing/js/jquery.easing",
        "mwheelIntent": "../bower_components/jScrollPane/script/mwheelIntent"
      },
      shim: {
        "jScrollPane": ["jquery", "jquery.mousewheel", "mwheelIntent", "jquery.easing"],
        "jquery": {exports: "jQuery"},
        "jquery.mousewheel": ["jquery"],
        "jquery.easing": ["jquery"],
        "mwheelIntent": ["jquery"]
      }
    });

**Comment by gdsmith** [comment]
Should be fixed now
